# Generated by Django 3.1.2 on 2020-10-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0003_auto_20201006_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
