# Generated by Django 3.1.2 on 2020-10-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0004_auto_20201006_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_has_size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_products.category'),
        ),
    ]
