# Generated by Django 3.1.2 on 2020-10-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0007_auto_20201015_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_has_size',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
