# Generated by Django 3.1.2 on 2020-10-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0008_auto_20201017_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_has_size',
        ),
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
